name: Syncer
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
permissions:
  contents: write
  packages: write
jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nobidev/git-syncer
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - run: git-syncer
        working-directory: /app
        env:
          GITHUB_UPSTREAM_REPOSITORY: opensignlabs/opensign
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
